### ISSUE TITLE
herokaiOnlyHandler

### ISSUE THREAD

**Issue by mmowris** [heroku/node-heroku-bouncer#24]
Hey @jclem , how can I use herokaiOnlyHandler to only allow heroku.com emails? Bit of a node - newb here any help appreciated! 

app.use(bouncer({
  oAuthClientID      : process.env.HEROKU_OAUTH_ID,
  oAuthClientSecret  : process.env.HEROKU_OAUTH_SECRET,
  encryptionSecret   : process.env.HEROKU_ENCRYPTION_SECRET,
  herokaiOnlyHandler : ???
}));

**Comment by jclem** [comment]
I don't really work on this or at @heroku, anymore, but you can provide it with a function that looks like Express middleware (`function bounce(req, res, next)`).

**Comment by mmowris** [comment]
Hey thanks @jclem , figured it out before I saw this response but thanks for the reply 👍 !
